# Generated by Django 3.2 on 2022-06-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('Employee', 'Employee'), ('Executive', 'Executive'), ('Manager', 'Manager')], default='Employee', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_amount', models.PositiveIntegerField()),
                ('sales_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.salesexecutive')),
            ],
        ),
    ]
