# Generated by Django 3.2 on 2022-06-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='sales_executive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sales', to='base.salesexecutive'),
        ),
    ]
